In [1]:
import pandas as pd
import numpy as np

In [98]:
movies = pd.read_csv('ml-32m/movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [99]:
movies.shape

(87585, 3)

In [100]:
#filtred_movies = movies[movies.movieId<10000]
filtred_movies = movies

In [102]:
ratings = pd.read_csv('ml-32m/ratings.csv', nrows=2000000)
ratings.head()

   userId  movieId  rating  timestamp
0       1       17     4.0  944249077
1       1       25     1.0  944250228
2       1       29     2.0  943230976
3       1       30     5.0  944249077
4       1       32     5.0  943228858

In [103]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 61.0 MB

In [104]:
len(ratings.userId.unique())

12773

In [105]:
max(ratings.movieId)

292467

In [106]:
merged_data = pd.merge(ratings, filtred_movies[['movieId', 'title']], on='movieId')

In [107]:
merged_data.shape

(2000000, 5)

In [108]:
merged_data.userId= merged_data.userId.astype(np.int32)

In [109]:
merged_data.movieId = merged_data.movieId.astype(np.int32)

In [110]:
merged_data.rating = merged_data.rating.round().astype(np.int32)

In [111]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 5 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int32
 1   movieId    int32
 2   rating     int32
 3   timestamp  int64
 4   title      object
dtypes: int32(3), int64(1), object(1)
memory usage: 53.4+ MB

In [112]:
grouped = merged_data.groupby(['userId', 'title'], observed=True)['rating'].mean().astype(np.int32)

In [113]:
user_item_matrix = grouped.unstack('title', fill_value=0)

In [ ]:
#user_item_matrix = merged_data.pivot_table(index='userId', columns='title', values='rating', fill_value=0)

In [114]:
user_item_matrix.shape

(12773, 36557)

In [115]:
user_item_matrix

title,(2019),"""Great Performances"" Cats (1998)","""Sr."" (2022)",#1 Cheerleader Camp (2010),#Alive (2020),#FollowMe (2019),#Horror (2015),#UNFIT: The Psychology of Donald Trump (2019),#cats_the_mewvie (2020),#realityhigh (2017),...,Он вам не Димон (2017),Оно (1990),Приключения Домовёнка (1986),Свадьба (1944),Сердца трех (1992),Снежные дорожки (1963),Цветик-семицветик (1948),Я худею (2018),キサラギ (2007),貞子3D (2012)
userId,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12769,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12770,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12771,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12772,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12773,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [116]:
user_item_matrix = user_item_matrix.loc[user_item_matrix.astype(bool).sum(axis=1) >= 50, user_item_matrix.astype(bool).sum(axis=0) >= 300]

In [117]:
user_item_matrix.shape

(8059, 1514)

In [118]:
user_item_matrix.head(20)

title,(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),12 Years a Slave (2013),127 Hours (2010),13 Going on 30 (2004),"13th Warrior, The (1999)",...,Young Frankenstein (1974),Young Guns (1988),Zero Dark Thirty (2012),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,4,0,0,...,0,0,0,2,3,4,0,0,2,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,4,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,4,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,4,0,4,0,4,0,0,0,3,3,...,4,4,4,4,5,4,4,4,3,3
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0

In [119]:
user_item_matrix.to_csv('UI_data_2.csv')

In [120]:
fill_rate = user_item_matrix.astype(bool).sum().sum() / user_item_matrix.size
fill_rate_percentage = fill_rate * 100
print(f"Заполненность матрицы: {fill_rate_percentage:.2f}%")

Заполненность матрицы: 10.14%