In [1]:
from MovieRecommendation import MovieRecommendation as mr
import pandas as pd
import numpy as np

In [3]:
# Генерация случайных данных для 25 пользователей и 10 фильмов
np.random.seed(42)  # Для воспроизводимости
m = 12535
n = 940
data = np.random.randint(0, 5, size=(m, n))

# Названия фильмов
movies = [f"Movie {i+1}" for i in range(n)]

# Индексы пользователей
users = [f"User {i+1}" for i in range(m)]

# Создаем DataFrame
data = pd.DataFrame(data, index=users, columns=movies)

data.head()  # Показать первые 5 строк

,Movie 1,Movie 2,Movie 3,Movie 4,Movie 5,Movie 6,Movie 7,Movie 8,Movie 9,Movie 10,...,Movie 931,Movie 932,Movie 933,Movie 934,Movie 935,Movie 936,Movie 937,Movie 938,Movie 939,Movie 940
User 1,3,4,2,4,4,1,2,2,2,4,...,1,0,1,2,4,0,0,0,0,0
User 2,1,4,2,2,2,2,1,3,4,0,...,2,4,2,0,0,4,0,3,1,4
User 3,2,3,4,0,0,0,0,2,3,1,...,2,0,2,0,3,2,3,3,1,0
User 4,4,0,4,0,3,2,2,1,4,4,...,0,1,2,0,4,0,4,3,3,4
User 5,2,0,0,3,4,0,0,2,1,3,...,4,0,1,2,1,1,0,1,3,1

In [7]:
data = pd.read_csv('UI_data.csv', index_col='userId')

In [5]:
data.head()

,'Til There Was You (1997),1-900 (06) (1994),2 Days in the Valley (1996),2001: A Space Odyssey (1968),"301, 302 (301/302) (1995)","39 Steps, The (1935)",8 Seconds (1994),A Walk in the Sun (1945),Above the Rim (1994),Ace Ventura: Pet Detective (1994),...,With Honors (1994),"Wizard of Oz, The (1939)",Wolf (1994),"Women, The (1939)","Wonderful, Horrible Life of Leni Riefenstahl, The (Macht der Bilder: Leni Riefenstahl, Die) (1993)","Wooden Man's Bride, The (Yan shen) (1994)","World of Apu, The (Apur Sansar) (1959)",Wyatt Earp (1994),"Yes, Madam (a.k.a. Police Assassins) (a.k.a. In the Line of Duty 2) (Huang gu shi jie) (1985)","Young Poisoner's Handbook, The (1995)"
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
data.shape

(12535, 940)

In [10]:
recommender = mr(n_recommendations=5, test=True, rank=500)
recommender.fit(data)

In [12]:
recomended = recommender.recommend(user=201)

print(recomended, '\n', len(recomended), '\n', len(recommender.unseen))

['Welcome to the Dollhouse (1995)', 'City Slickers (1991)', 'EDtv (1999)', 'Whole Nine Yards, The (2000)', 'Three Days of the Condor (3 Days of the Condor) (1975)']
 5
 4568